### ISSUE TITLE
Couldn't find this library in PyPI

### ISSUE THREAD

**Issue by Kroisse** [ceronman/typeannotations#7]
I've searched some Python 3 libraries to typecheck using the function annotation, and found this library. I was fascinated by its features, but I got a problem that it wasn't yet uploaded on Python Package Index(PyPI), so I couldn't install it with `pip install typeannotations`, and couldn't simply include it as a dependency. Therefore it becomes a huge burden for maintainability. `setup.py` was already included in this repository, However, I wonder the reason it wasn't distributed on PyPI.

If you're just deferring the distribution, I wish to mention that anyone can register their packages on PyPI with any unused name without any verifications, and if the name was taken once, it cannot be released as unused until the owner who took the name firstly will drop it or yield it. That's why [Pillow](https://pypi.python.org/pypi/Pillow) have to use different name instead of [PIL](https://pypi.python.org/pypi/PIL), and the current maintainer of [setuptools](https://pypi.python.org/pypi/setuptools) had released its enhanced version as a different name, [distribute](https://pypi.python.org/pypi/distribute). So if you're willing to upload this library as `typeannotations`, I suggest doing it as quick as possible to acquire the name. Although your first release is `0.1.0` or less, it's ok to me. I can deal with it and many people also will do.

This is a great library that will be applicable immediately (unlike mypy), so It can be very helpful to many Python 3 users by a little effort. Please consider uploading it on PyPI.

**Comment by dahlia** [comment]
+1

**Comment by item4** [comment]
+1

**Comment by ceronman** [comment]
Sorry for the delay guys! I was on vacation. Here is the PyPi link:

https://pypi.python.org/pypi/typeannotations/0.1.0

Thanks for reporting the bug!

**Comment by dahlia** [comment]
:+1: Thank you!

**Comment by dahlia** [comment]
Oh, it lacks the file.  You need to upload a tarball file using `setup.py sdist upload` command.

**Comment by dahlia** [comment]
Also it would be better if it’s packaged using [wheel](http://pythonwheels.com/).  You can create a wheel package and then upload it to PyPI using the following instruction:

``` console
$ pip install wheel
$ python setup.py bdist_wheel upload
```

**Comment by ceronman** [comment]
Hi, I just pushed the tarball. I'm getting some errors using wheel. I'll check it out later and maybe I'll upload a wheel version too. Cheers.

**Comment by dahlia** [comment]
Thanks!
